# Generated by Django 5.2.2 on 2025-06-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shortening_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedlink',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
