# Generated by Django 5.2.2 on 2025-06-07 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shortening_link', '0002_shortenedlink_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api_shortening_link.shortenedlink')),
            ],
        ),
    ]
